# Site infos
site_name: 'PHP Telegram Bot Documentation'
site_description: 'A pure PHP Telegram Bot, fully extensible via plugins.'
# site_url: the .io/docs url of the gh-pages
copyright: 'MIT License'

# Repo infos
repo_name: 'PHP Telegram Bot'
repo_url: 'https://github.com/php-telegram-bot/core'
edit_uri: 'https://github.com/php-telegram-bot/docs/edit/develop/docs'

pages:
  - Home: index.md

  - Let's Play!:
    - Introduction: start/introduction.md
    - Environment: start/environment.md
    - Registering your bot: start/registering.md
    - First steps with the code: start/first-steps.md

  - Core:
    - Introduction: core/introduction.md

  - About: about.md
  - Contributing guidelines: guidelines.md
  - Code playground: code-playground.md


# Theme and its options
#https://squidfunk.github.io/mkdocs-material/
theme: 'material'
extra:
  palette:
    primary: 'blue'
    accent: 'cyan'

extra_css:
  - stylesheets/extra.css

# Extensions with reference url
markdown_extensions:
    - smarty
    - admonition

    #https://pythonhosted.org/Markdown/extensions/abbreviations.html
    - abbr

    #https://pythonhosted.org/Markdown/extensions/definition_lists.html
    - def_list

    #https://pythonhosted.org/Markdown/extensions/footnotes.html
    - footnotes

    #https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png

    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.escapeall

    - pymdownx.snippets:
        base_path: 'extra'

    - pymdownx.highlight:
        css_class: codehilite
        extend_pygments_lang:
          - name: php
            lang: php
            options:
              startinline: true
          - name: shell
            lang: console
